/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application resource file(s). For more   */
/*  information please refer to the GUIX Studio user's guide, or visit our web */
/*  site at www.expresslogic.com.                                              */
/*                                                                             */
/*  GUIX Studio Revision 5.4.2.9                                               */
/*  Date (dd.mm.yyyy): 30.10.2019   Time (hh:mm): 21:36                        */
/*******************************************************************************/


#ifndef _GUIAPP_DISPLAY_1_RESOURCES_H_
#define _GUIAPP_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 256
#define DISPLAY_1_Y_RESOLUTION 320
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_CANVAS 0
#define GX_COLOR_ID_WIDGET_FILL 1
#define GX_COLOR_ID_WINDOW_FILL 2
#define GX_COLOR_ID_DEFAULT_BORDER 3
#define GX_COLOR_ID_WINDOW_BORDER 4
#define GX_COLOR_ID_TEXT 5
#define GX_COLOR_ID_SELECTED_TEXT 6
#define GX_COLOR_ID_SELECTED_FILL 7
#define GX_COLOR_ID_SHADOW 8
#define GX_COLOR_ID_SHINE 9
#define GX_COLOR_ID_BTN_BORDER 10
#define GX_COLOR_ID_BTN_UPPER 11
#define GX_COLOR_ID_BTN_LOWER 12
#define GX_COLOR_ID_BTN_TEXT 13
#define GX_COLOR_ID_SCROLL_FILL 14
#define GX_COLOR_ID_SCROLL_BUTTON 15
#define GX_COLOR_ID_TEXT_INPUT_TEXT 16
#define GX_COLOR_ID_TEXT_INPUT_FILL 17
#define GX_COLOR_ID_SLIDER_TICK 18
#define GX_COLOR_ID_SLIDER_GROOVE_TOP 19
#define GX_COLOR_ID_SLIDER_GROOVE_BOTTOM 20
#define GX_COLOR_ID_SLIDER_NEEDLE_OUTLINE 21
#define GX_COLOR_ID_SLIDER_NEEDLE_FILL 22
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE1 23
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE2 24
#define GX_COLOR_ID_DISABLED_TEXT 25
#define GX_COLOR_ID_DISABLED_FILL 26
#define GX_COLOR_ID_READONLY_TEXT 27
#define GX_COLOR_ID_READONLY_FILL 28
#define DISPLAY_1_COLOR_TABLE_SIZE 29

/* Font ID definitions                                                         */

#define GX_FONT_ID_SYSTEM 0
#define GX_FONT_ID_BUTTON 1
#define GX_FONT_ID_PROMPT 2
#define GX_FONT_ID_TEXT_INPUT 3
#define DISPLAY_1_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_RADIO_ON 1
#define GX_PIXELMAP_ID_RADIO_OFF 2
#define GX_PIXELMAP_ID_CHECKBOX_ON 3
#define GX_PIXELMAP_ID_CHECKBOX_OFF 4
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 5

/* String Ids                                                                  */

#define GX_STRING_ID_PRINCIPAL 1
#define GX_STRING_ID_DIAGNOSTICOS 2
#define GX_STRING_ID_WINDOW2 3
#define GX_STRING_ID_DUTY_CYCLE 4
#define GX_STRING_ID_PROJECT_TEXT 5
#define GX_STRING_ID_PROJECT_TEXT_2 6
#define GX_STRING_ID_SPEED 7
#define GX_STRING_ID_SW_VERSION 8
#define GX_STRING_ID_HW_VERSION 9
#define GX_STRING_ID_HW_VERSION_2 10
#define GX_STRING_ID_PROGRAMERS_1 11
#define GX_STRING_ID_PROGRAMERS_2 12
#define GX_STRING_ID_SET_POINT 13
#define GX_STRING_ID_DIAGNOSTICOS_1 14
#define GX_STRING_ID_SHORT_MESSAGE_1 15
#define GX_STRING_ID_SHORT_MESSAGE_2 16
#define GX_STRING_ID_STRING_1 17
#define GX_STRING_ID_STRING_2 18
#define GX_STRING_ID_STRING_3 19
#define GX_STRING_ID_STRING_4 20
#define GX_STRING_ID_STRING_5 21
#define GX_STRING_ID_STRING_6 22
#define GX_STRING_ID_STRING_7 23
#define GX_STRING_ID_STRING_8 24
#define GX_STRING_ID_STRING_9 25
#define GX_STRING_ID_STRING_10 26
#define GX_STRING_ID_STRING_11 27
#define GX_STRING_ID_STRING_12 28
#define GX_STRING_ID_STRING_13 29
#define GX_STRING_ID_STRING_14 30
#define GX_STRING_ID_STRING_15 31
#define DISPLAY_1_STRING_TABLE_SIZE 32

#endif                                       /* sentry                         */
