#define DC_UPDATE_EVENT 53
#define SPEED_UPDATE_EVENT 54
#define SETPOINT_UPDATE_EVENT 55
#define SWVERSION_UPDATE_EVENT 56
#define SHORT_BATTERY_UPDATE_EVENT 57
#define SHORT_GROUND_UPDATE_EVENT 58
#define NO_SHORT_UPDATE_EVENT 59

#define MAX_SPEED 3000
